"""Independent validation of ``compat/upstream_test_inventory_0013.json``.

The inventory is generated by ``tools/inventory_upstream_tests_0013.py`` from
the vendored pinned LanguageTool 6.8 JUnit sources.  This module re-derives the
facts it can from those sources with an independent scan and fails closed on any
drift, missing mapping, dangling Python test reference or forbidden status.
"""

from __future__ import annotations

import hashlib
import json
import re
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
INVENTORY = REPO_ROOT / "compat" / "upstream_test_inventory_0013.json"
VENDOR = REPO_ROOT / "third_party" / "languagetool"
ORACLE_FIXTURE = REPO_ROOT / "tests" / "fixtures" / "oracle_upstream_tests_0013.json"

PINNED_COMMIT = "e807fcde6a6506191e1470744d2345da28c26be6"
RU_MODULE = "languagetool-language-modules/ru"

ALLOWED_STATUS = {
    "DIRECT_PYTHON_PARITY",
    "ORACLE_PARITY",
    "ALREADY_COVERED_EQUIVALENTLY",
    "NOT_EXECUTABLE_HELPER",
    "LANGUAGE_MODEL_DEFERRED",
    "NOT_APPLICABLE_WITH_PROOF",
    "BLOCKED",
}

# A status that may end an executable @Test method's accounting.
EXECUTABLE_STATUS = ALLOWED_STATUS - {"NOT_EXECUTABLE_HELPER", "BLOCKED"}

_TEST_METHOD_RE = re.compile(
    r"@Test\b[^;{]*?\b(?:public|protected|private)\s+(?:final\s+)?\w[\w.<>\[\]]*\s+(\w+)\s*\(",
    re.S,
)


@pytest.fixture(scope="module")
def inventory() -> dict:
    return json.loads(INVENTORY.read_text(encoding="utf-8"))


def test_pinned_upstream_identity(inventory: dict) -> None:
    assert inventory["schema_version"] == "1.0.0"
    assert inventory["task"] == "0013_complete_upstream_russian_test_parity"
    assert inventory["generated_by"] == "tools/inventory_upstream_tests_0013.py"
    assert inventory["pinned_upstream"]["commit"] == PINNED_COMMIT
    assert inventory["pinned_upstream"]["tag"] == "v6.8"
    assert set(inventory["status_enum"]) == ALLOWED_STATUS
    assert inventory["counting_rule"]["fail_closed"]


def test_russian_module_file_inventory_matches_pinned_tree(inventory: dict) -> None:
    """Exactly the pinned Russian-module test files, byte for byte."""
    on_disk = sorted(
        path.relative_to(VENDOR).as_posix()
        for path in (VENDOR / RU_MODULE / "src" / "test").rglob("*.java")
    )
    recorded = sorted(entry["source_path"] for entry in inventory["russian_module_test_files"])
    assert recorded == on_disk
    assert len(recorded) == 18

    for entry in inventory["russian_module_test_files"]:
        path = VENDOR / entry["source_path"]
        raw = path.read_bytes()
        assert entry["source_size_bytes"] == len(raw), entry["source_path"]
        assert entry["source_sha256"] == hashlib.sha256(raw).hexdigest(), entry["source_path"]
        assert entry["module"] == RU_MODULE
        source = raw.decode("utf-8")
        simple = entry["java_class"].rsplit(".", 1)[1]
        assert path.name == f"{simple}.java"
        assert re.search(rf"\bclass\s+{simple}\b", source), entry["source_path"]
        assert entry["file_classification"] in ("EXECUTABLE_TEST_CLASS", "FIXTURE_ONLY_SUBCLASS")


def test_declared_test_methods_match_independent_scan(inventory: dict) -> None:
    """Re-derive the locally declared @Test methods with an independent regex."""
    for entry in inventory["russian_module_test_files"]:
        source = (VENDOR / entry["source_path"]).read_text(encoding="utf-8")
        source = re.sub(r"//[^\n]*", "", source)
        source = re.sub(r"/\*.*?\*/", "", source, flags=re.S)
        scanned = sorted(set(_TEST_METHOD_RE.findall(source)))
        recorded = sorted(m["method"] for m in entry["declared_test_methods"])
        assert recorded == scanned, entry["source_path"]


def test_executable_methods_are_fully_mapped(inventory: dict) -> None:
    closure = {record["key"]: record for record in inventory["contract_closure"]}
    executable = [
        method
        for entry in inventory["russian_module_test_files"]
        for method in entry["declared_test_methods"] + entry["inherited_test_methods"]
    ]
    assert len(executable) == inventory["totals"]["executable_methods_total"] == 24
    for method in executable:
        assert method["is_test"] is True, method["key"]
        record = closure.get(method["key"])
        assert record is not None, f"unmapped executable method: {method['key']}"
        assert record["status"] in EXECUTABLE_STATUS, method["key"]
        assert record["semantics"], method["key"]
        assert record["scenario_units"] == method["scenario_units"]


def test_contract_closure_integrity(inventory: dict) -> None:
    closure = inventory["contract_closure"]
    keys = [record["key"] for record in closure]
    assert len(keys) == len(set(keys)), "duplicate contract identity"
    for record in closure:
        assert record["status"] in ALLOWED_STATUS, record["key"]
        assert record["status"] != "BLOCKED", record["key"]
        assert record["semantics"], record["key"]
        assert record["scenario_units"] >= 0
        if record["status"] == "NOT_EXECUTABLE_HELPER":
            # Derived automatically, and only for zero-unit non-@Test plumbing.
            assert record["scenario_units"] == 0, record["key"]
            assert record["is_test"] is False, record["key"]
            assert record.get("derived") is True, record["key"]
        else:
            # Any other status must be an explicitly authored mapping entry.
            assert record.get("derived") is not True, record["key"]
        if record["status"] == "NOT_APPLICABLE_WITH_PROOF":
            assert record.get("reason"), record["key"]
        if record["status"] == "LANGUAGE_MODEL_DEFERRED":
            assert "RussianConfusionProbabilityRule" in record.get("reason", ""), record["key"]
        # Source binding for every contract.
        path = VENDOR / record["declaring_source_path"]
        assert path.is_file(), record["key"]
        assert hashlib.sha256(path.read_bytes()).hexdigest() == record["declaring_source_sha256"]


def test_language_model_deferral_is_the_only_lm_bucket(inventory: dict) -> None:
    deferred = [r for r in inventory["contract_closure"] if r["status"] == "LANGUAGE_MODEL_DEFERRED"]
    assert len(deferred) == 1
    assert deferred[0]["key"] == "org.languagetool.LanguageSpecificTest#testConfusionSetLoading/0"


def _assert_python_reference_exists(reference: str) -> None:
    file_part, _, node = reference.partition("::")
    path = REPO_ROOT / file_part
    assert path.is_file(), f"missing Python test file: {file_part}"
    if node:
        source = path.read_text(encoding="utf-8")
        assert re.search(rf"^def {re.escape(node)}\(", source, re.M), (
            f"missing Python test function: {reference}"
        )


def test_every_python_mapping_reference_resolves(inventory: dict) -> None:
    references = set()
    for record in inventory["contract_closure"]:
        references.update(record["python_tests"])
    for entry in inventory["generic_core_evidence_sources"]:
        references.update(entry["python_tests"])
    assert references
    for reference in sorted(references):
        _assert_python_reference_exists(reference)


def test_generic_core_evidence_is_reconciled(inventory: dict) -> None:
    entries = inventory["generic_core_evidence_sources"]
    assert len(entries) == 13
    oracle_ids = [case["id"] for case in json.loads(ORACLE_FIXTURE.read_text(encoding="utf-8"))["cases"]]
    for entry in entries:
        path = VENDOR / entry["source_path"]
        assert path.is_file(), entry["source_path"]
        raw = path.read_bytes()
        assert entry["source_size_bytes"] == len(raw)
        assert entry["source_sha256"] == hashlib.sha256(raw).hexdigest()
        assert entry["status"] in ALLOWED_STATUS
        assert entry["status"] != "BLOCKED"
        assert entry["russian_dependency"]
        assert entry["reason"]
        assert entry["test_method_count"] == len(entry["test_methods"]) > 0
        if entry["status"] == "ORACLE_PARITY":
            prefix = entry["oracle_case_prefix"]
            assert any(case_id.startswith(prefix) for case_id in oracle_ids), prefix
        if entry["status"] in ("ORACLE_PARITY", "ALREADY_COVERED_EQUIVALENTLY", "DIRECT_PYTHON_PARITY"):
            assert entry["python_tests"], entry["source_path"]


def test_tagger_dictionary_audit_matches_packaged_dictionary(inventory: dict) -> None:
    audit = inventory["tagger_dictionary_audit"]
    path = REPO_ROOT / audit["dictionary_path"]
    raw = path.read_bytes()
    assert audit["dictionary_size_bytes"] == len(raw)
    assert audit["dictionary_sha256"] == hashlib.sha256(raw).hexdigest()
    assert audit["entries_total"] == 7_176_385
    assert audit["entries_without_pos_tag"] == 0
    assert (REPO_ROOT / audit["tool"]).is_file()


def test_totals_are_consistent_and_complete(inventory: dict) -> None:
    totals = inventory["totals"]
    closure = inventory["contract_closure"]
    assert totals["russian_module_test_files_total"] == 18
    assert totals["russian_module_test_files_accounted"] == 18
    assert totals["executable_methods_total"] == totals["executable_methods_mapped"] == 24
    assert totals["contract_closure_total"] == len(closure)
    assert totals["contract_scenario_units_total"] == sum(r["scenario_units"] for r in closure)
    assert totals["contract_assertion_units_total"] == sum(r["assertion_units"] for r in closure)
    assert totals["blocked"] == 0
    assert totals["unmapped"] == 0
    assert totals["unknown"] == 0
    assert totals["ordinary_non_lm_contracts_total"] == totals["ordinary_non_lm_contracts_mapped"]
    assert (totals["ordinary_non_lm_scenario_units_total"]
            == totals["ordinary_non_lm_scenario_units_mapped"])
    assert totals["generic_core_evidence_sources_total"] == 13
    assert (totals["generic_core_evidence_sources_reconciled"]
            == totals["generic_core_evidence_sources_total"])
    counts = totals["status_counts"]
    assert set(counts) == ALLOWED_STATUS
    assert sum(counts.values()) == len(closure)
    assert counts["BLOCKED"] == 0
    assert counts["LANGUAGE_MODEL_DEFERRED"] == 1


def test_inventory_is_deterministically_regenerable(inventory: dict) -> None:
    """Re-running the extractor over the pinned sources must reproduce the file."""
    from tools.inventory_upstream_tests_0013 import build

    assert build() == inventory


def test_vector_loop_counts_match_pinned_literals(inventory: dict) -> None:
    """The only pinned vector loops are the two RussianVerbConjugationRule sets."""
    loops = [
        (record["key"], loop)
        for record in inventory["contract_closure"]
        for loop in record["vector_loops"]
    ]
    assert len(loops) == 2
    by_field = {loop["field"]: loop for _, loop in loops}
    assert by_field["wrongSentences"]["elements"] == 19
    assert by_field["rightSentences"]["elements"] == 22
    for _, loop in loops:
        assert loop["units_per_element"] == 1
